on: push
name: 'Release Vscode Plugin'
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        uses: actions/npm@master
        with:
          args: install --unsafe-perm
      - name: Vscode release plugin
        uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
